"""
Storage backend for the resume store.

One schema, two dialects. Set DATABASE_URL to a Postgres connection string
(Neon, Supabase, anything) and it uses Postgres; leave it unset and it falls
back to the local SQLite file, so the app still runs with no network.

    DATABASE_URL=postgresql://user:pass@ep-xxx.aws.neon.tech/neondb?sslmode=require

SQL is written once with `?` placeholders and translated for Postgres. Every
INSERT that needs its new id uses RETURNING, which both engines support
(SQLite 3.35+; this machine has 3.41).
"""
from __future__ import annotations

import os
import sqlite3
from contextlib import contextmanager
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).parent
SQLITE_PATH = ROOT / "resume.db"


def load_dotenv(path: Path = ROOT / ".env") -> None:
    """Minimal .env reader — keeps the connection string out of the shell history."""
    if not path.exists():
        return
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        key, val = key.strip(), val.strip().strip('"').strip("'")
        os.environ.setdefault(key, val)


load_dotenv()

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
IS_PG = DATABASE_URL.startswith(("postgres://", "postgresql://"))

# A serverless function is frozen between requests and replaced without notice,
# so a client-side pool is worse than none: every warm instance holds its own
# connections and Neon's limit goes first. Neon's -pooler endpoint is PgBouncer,
# which already pools server-side — so there we open one connection per request
# and let the pooler do the work. A long-lived process keeps the real pool.
SERVERLESS = bool(os.environ.get("VERCEL") or os.environ.get("AWS_LAMBDA_FUNCTION_NAME"))

SCHEMA_SQLITE = """
CREATE TABLE IF NOT EXISTS profile (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    name        TEXT    NOT NULL,
    description TEXT,
    created_at  INTEGER NOT NULL,
    deleted_at  INTEGER
);
-- Name uniqueness is a partial index over live rows only (a deleted profile
-- must not keep its name reserved). It is created by migrate_soft_delete(),
-- which runs after the column is guaranteed to exist.
CREATE TABLE IF NOT EXISTS document (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    profile_id INTEGER NOT NULL REFERENCES profile(id) ON DELETE CASCADE,
    name       TEXT    NOT NULL,
    html       TEXT    NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    deleted_at INTEGER
);
CREATE TABLE IF NOT EXISTS version (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    document_id INTEGER NOT NULL REFERENCES document(id) ON DELETE CASCADE,
    html        TEXT    NOT NULL,
    label       TEXT,
    created_at  INTEGER NOT NULL,
    deleted_at  INTEGER
);
CREATE INDEX IF NOT EXISTS version_doc_idx ON version(document_id, created_at DESC);
CREATE INDEX IF NOT EXISTS document_profile_idx ON document(profile_id, updated_at DESC);
"""

SCHEMA_PG = """
CREATE TABLE IF NOT EXISTS profile (
    id          BIGGENERATED,
    name        TEXT   NOT NULL,
    description TEXT,
    created_at  BIGINT NOT NULL,
    deleted_at  BIGINT
);
CREATE TABLE IF NOT EXISTS document (
    id         BIGGENERATED,
    profile_id BIGINT NOT NULL REFERENCES profile(id) ON DELETE CASCADE,
    name       TEXT   NOT NULL,
    html       TEXT   NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    deleted_at BIGINT
);
CREATE TABLE IF NOT EXISTS version (
    id          BIGGENERATED,
    document_id BIGINT NOT NULL REFERENCES document(id) ON DELETE CASCADE,
    html        TEXT   NOT NULL,
    label       TEXT,
    created_at  BIGINT NOT NULL,
    deleted_at  BIGINT
);
CREATE INDEX IF NOT EXISTS version_doc_idx ON version(document_id, created_at DESC);
CREATE INDEX IF NOT EXISTS document_profile_idx ON document(profile_id, updated_at DESC);
""".replace("BIGGENERATED", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")


class Cx:
    """Thin cursor-returning wrapper that hides the placeholder dialect."""

    def __init__(self, raw, pg: bool):
        self.raw = raw
        self.pg = pg

    def execute(self, sql: str, params=()):
        if self.pg:
            cur = self.raw.cursor()
            cur.execute(sql.replace("?", "%s"), params)
            return cur
        return self.raw.execute(sql, params)


_pool = None


def _pg_pool():
    """Lazily built pool.

    Neon suspends an idle compute, so a pooled connection can be dead by the
    time we reach for it. `check_connection` validates on checkout and the pool
    transparently opens a fresh one, which is what keeps this stable across
    long gaps between edits.
    """
    global _pool
    if _pool is None:
        from psycopg.rows import dict_row
        from psycopg_pool import ConnectionPool

        _pool = ConnectionPool(
            DATABASE_URL,
            min_size=1,
            max_size=4,
            timeout=20,               # room for a Neon cold start
            max_idle=120,
            check=ConnectionPool.check_connection,
            kwargs={"row_factory": dict_row, **PG_KWARGS},
            open=True,
        )
    return _pool


PG_KWARGS = {
    "connect_timeout": 15,
    "keepalives": 1,
    "keepalives_idle": 30,
    "application_name": "resume-store",
    # Neon's -pooler endpoint is PgBouncer in transaction mode, which cannot
    # carry server-side prepared statements between transactions. Without this
    # you get "prepared statement _pg3_N already exists" after a few calls.
    "prepare_threshold": None,
}


@contextmanager
def db():
    if IS_PG and SERVERLESS:
        import psycopg
        from psycopg.rows import dict_row

        con = psycopg.connect(DATABASE_URL, row_factory=dict_row, **PG_KWARGS)
        try:
            yield Cx(con, True)
            con.commit()
        finally:
            con.close()
    elif IS_PG:
        with _pg_pool().connection() as con:   # commits on clean exit
            yield Cx(con, True)
    else:
        con = sqlite3.connect(SQLITE_PATH)
        con.row_factory = sqlite3.Row
        con.execute("PRAGMA foreign_keys = ON")
        try:
            yield Cx(con, False)
            con.commit()
        finally:
            con.close()


def init_db() -> None:
    if IS_PG:
        with db() as cx:
            for stmt in filter(str.strip, SCHEMA_PG.split(";")):
                cx.execute(stmt)
    else:
        con = sqlite3.connect(SQLITE_PATH)
        con.execute("PRAGMA journal_mode = WAL")
        con.executescript(SCHEMA_SQLITE)
        con.commit()
        con.close()


def backend() -> dict:
    """What the UI badge reports."""
    if not IS_PG:
        return {"backend": "sqlite", "target": SQLITE_PATH.name}
    host = urlparse(DATABASE_URL).hostname or ""
    if "neon.tech" in host:
        name = "neon"
    elif "supabase" in host:
        name = "supabase"
    else:
        name = "postgres"
    return {"backend": name, "target": host}


def fix_pg_sequences() -> None:
    """After a migration that carried explicit ids, move the identity sequences
    past them so the next INSERT does not collide."""
    if not IS_PG:
        return
    with db() as cx:
        for table in ("document", "version"):
            cx.execute(
                f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), "
                f"COALESCE((SELECT MAX(id) FROM {table}), 1))"
            )
